### ISSUE TITLE
Error on uploading the model (ImportError: cannot import name 'ConcatenateIterator' from 'cog)

### ISSUE THREAD

**Issue by mrloldev** [replicate/cog-llama#7]
Following error:
```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.16/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/.pyenv/versions/3.8.16/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/cog/command/openapi_schema.py", line 26, in <module>
    app = create_app(predictor_ref)
  File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/cog/server/http.py", line 46, in create_app
    predictor = load_predictor_from_ref(predictor_ref)
  File "/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/cog/predictor.py", line 91, in load_predictor_from_ref
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "predict.py", line 7, in <module>
    from cog import BasePredictor, ConcatenateIterator, Input, Path
ImportError: cannot import name 'ConcatenateIterator' from 'cog' (/root/.pyenv/versions/3.8.16/lib/python3.8/site-packages/cog/__init__.py)
```

**Comment by mrloldev** [comment]
cog version was outdated
